services:
  coolify:
    image: "${COOLIFY_REGISTRY_URL:-ghcr.io}/coollabsio/coolify:${COOLIFY_LATEST_IMAGE:-latest}"
    container_name: coolify
    restart: always
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - type: bind
        source: ./.env
        target: /var/www/html/.env
        read_only: true
      - /data/coolify/ssh:/var/www/html/storage/app/ssh
      - /data/coolify/applications:/var/www/html/storage/app/applications
      - /data/coolify/databases:/var/www/html/storage/app/databases
      - /data/coolify/services:/var/www/html/storage/app/services
      - /data/coolify/backups:/var/www/html/storage/app/backups
    environment:
      - APP_ENV=${COOLIFY_APP_ENV:-production}
      - APP_KEY=${COOLIFY_APP_KEY:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}
      - APP_NAME=${COOLIFY_APP_NAME:-Coolify}
      - PUSHER_APP_ID=${COOLIFY_PUSHER_APP_ID:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}
      - PUSHER_APP_KEY=${COOLIFY_PUSHER_APP_KEY:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}
      - PUSHER_APP_SECRET=${COOLIFY_PUSHER_APP_SECRET:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}
      - DB_CONNECTION=pgsql
      - DB_HOST=coolify-db
      - DB_PORT=5432
      - DB_DATABASE=${COOLIFY_DB_DATABASE:-coolify}
      - DB_USERNAME=${COOLIFY_DB_USERNAME}
      - DB_PASSWORD=${COOLIFY_DB_PASSWORD}
      - REDIS_HOST=coolify-redis
      - REDIS_PASSWORD=${COOLIFY_REDIS_PASSWORD}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - PHP_FPM_PM_CONTROL=${PHP_FPM_PM_CONTROL:-dynamic}
      - PHP_FPM_PM_START_SERVERS=${PHP_FPM_PM_START_SERVERS:-1}
      - PHP_FPM_PM_MIN_SPARE_SERVERS=${PHP_FPM_PM_MIN_SPARE_SERVERS:-1}
      - PHP_FPM_PM_MAX_SPARE_SERVERS=${PHP_FPM_PM_MAX_SPARE_SERVERS:-10}
    env_file:
      - ./.env
    ports:
      - "${COOLIFY_APP_PORT:-8000}:8080"
    expose:
      - "8080"
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - appnet
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      soketi:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: always
    volumes:
      - coolify-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${COOLIFY_DB_USERNAME:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
      POSTGRES_PASSWORD: "${COOLIFY_DB_PASSWORD:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
      POSTGRES_DB: "${COOLIFY_DB_DATABASE:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${COOLIFY_DB_USERNAME}", "-d", "${COOLIFY_DB_DATABASE}" ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${COOLIFY_REDIS_PASSWORD:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}
    environment:
      REDIS_PASSWORD: "${COOLIFY_REDIS_PASSWORD:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
    volumes:
      - coolify-redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${COOLIFY_REDIS_PASSWORD} ping" ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - appnet

  soketi:
    image: "${COOLIFY_REGISTRY_URL:-ghcr.io}/coollabsio/coolify-realtime:1.0.10"
    container_name: coolify-realtime
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    ports:
      - "${COOLIFY_SOKETI_PORT:-6001}:6001"
      - "6002:6002"
    volumes:
      - /data/coolify/ssh:/var/www/html/storage/app/ssh
    environment:
      APP_NAME: "${COOLIFY_APP_NAME:-Coolify}"
      SOKETI_DEBUG: "${COOLIFY_SOKETI_DEBUG:-false}"
      SOKETI_DEFAULT_APP_ID: "${COOLIFY_PUSHER_APP_ID:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
      SOKETI_DEFAULT_APP_KEY: "${COOLIFY_PUSHER_APP_KEY:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
      SOKETI_DEFAULT_APP_SECRET: "${COOLIFY_PUSHER_APP_SECRET:?set in VM - Manual App Deployment (Inside VM)/Coolify/.env}"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1" ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - appnet

volumes:
  coolify-db:
    name: coolify-db
  coolify-redis:
    name: coolify-redis

networks:
  appnet:
    name: appnet
    external: true
